import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Topbar from "./Components/Topbar";
import Header from "./Components/Header";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "400", "600", "700", "900"],
  variable: "--font-Inter",
});
export const metadata: Metadata = {
  title: "E-Commerce Figma Website",
  description: "Generated by Hammad Javed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${inter.variable} antialiased  bg-white`}
      >
        <Topbar />
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
